- [コルーチンのポイントまとめ](#コルーチンのポイントまとめ)


# コルーチンのポイントまとめ

例外伝搬のまとめ

- Job か SupervisorJob かにかかわらず、例外は必ずスローされる
- 親が SupervisorJob の場合は、例外は親で検出されますが、親のジョブがキャンセルされることはありません。
  - つまり、親の CoroutineExceptionHandler でも例外をキャッチすることが可能であるということ。
- 親が SupervisorJob の場合に、子で例外が発生した場合は、その子コルーチン内で例外がスローされます。


- コルーチンスコープは、コルーチンを開始できるスコープを定義しているだけであり、
  スコープ自体は、コルーチンを開始しているわけではない。
- コルーチンビルダーは、コルーチンを開始し、コルーチンスコープを定義する。
- Koltin のコルーチンを Java のスレッドに例えるなら、コルーチンスコープは、スレッドを開始できる場を提供し、コルーチン / コルーチンビルダー は、実際のスレッドを開始する。という意味がありそうだ。


- launch ビルダーで生成したコルーチンは、 Job.cancel() でキャンセルされた場合に、 CancellationException をスローしますが、この例外は、親に伝搬しません。そのため、親コルーチンは、キャンセルされません。これは、 CancellationException とその他の例外の重要な違いです。 (ただし、そもそも CancellationException はキャッチすべきではないとドキュメントには記載があります。しかし、キャンセル時になにか処理を実行したい場合もあると思うので、その場合は、 `isActive` でジョブの状態がアクティブかどうかを判定し、アクティブな場合のみ、コルーチンの処理が行われるよにしてください。)

```kotlin
val outerJob = launch {
    try {
        val innerJob = launch {
            try {
                Log.v("test", "Inner launch is suspending.")
                delay(Long.MAX_VALUE)
            } catch (e: CancellationException) {
                // このコルーチンは job.cancel でキャンセルされたコルーチンそのものなので、
                // CancellationException がキャッチできます。
                Log.v("test", "Inner launch is cancelled.")
            }
            Log.v("test", "Inner launch is finishing.")
        }
        delay(300)
        innerJob.cancelAndJoin()
    } catch (e: CancellationException) {
        // 親には CancellationException が伝搬しないため、
        // この catch ブロックは呼ばれません。
        Log.v("test", "Outer launch is cancelling.")
    }
    Log.v("test", "Outer launch is finishing.")
}
```

CancellationException をキャッチしたい場合の例

```kotlin
val job = launch(Dispatchers.Default) {
    var i = 0
    while (i < 10 && isActive) {
        try {
            println("job: I'm sleeping ${i++} ...")
            delay(500)
        } catch (e: Exception) {
            println(e)
        }
    }
}
delay(1300L)
println("main: I'm tired of waiting!")
job.cancelAndJoin()
println("main: Now I can quit.")
```

```
実行結果

job: I'm sleeping 0 ...
job: I'm sleeping 1 ...
job: I'm sleeping 2 ...
main: I'm tired of waiting!
kotlinx.coroutines.JobCancellationException: ～(長いので省略)
main: Now I can quit.
```

- CancellationException は、キャッチしてはいけない。キャッチすると、コルーチンの処理が中断できずに最後まで実行されてしまうため。 ( [参考資料](./03.キャンセルとタイムアウト.md/#2-cancellationexception-をキャッチしてしまっている場合) )
- launch ビルダーで生成したコルーチンは、 CancellationException 以外の例外が発生した場合は、発生した例外を親コルーチンに伝搬します。親コルーチンは伝搬してきた例外を起因として、その Job をキャンセル状態にします。ただし、親が Supervisor の場合は、親に例外を伝搬せず、親や兄弟はキャンセル状態になりません。















