- [例外](#例外)
  - [基本形](#基本形)
  - [Kotlin には検査例外が存在しない](#kotlin-には検査例外が存在しない)
  - [複数の例外を処理したい場合](#複数の例外を処理したい場合)
  - [ある例外を別の例外でラップする](#ある例外を別の例外でラップする)


# 例外

## 基本形

基本的に Java の場合と記述方法は同じようです。

```Kotlin
throw IllegalArgumentException("A percentage must be between 0 and 100 [parameter: $percentage]")
```


## Kotlin には検査例外が存在しない

Kotlin には検査例外が存在しないらしい。

コンパイル時に `try {} catch() {}` や、メソッド呼び出し元への `throw` がなくても、コンパイルが通ってしまい、実行時エラーになるらしい。


## 複数の例外を処理したい場合

```kotlin
try {
    // ...
} catch (e: Exception) {
    when(e) {
        is IOException, is ClassNotFoundException -> {
            // ...
        }
        else -> throw e
    }
}
```


## ある例外を別の例外でラップする

Kotlin では例外を別の例外でラップすることが可能です。これは、例外チェーンを構築するためによく使われます。 Kotlin の Throwable クラスはコンストラクタで「原因」（ cause ）を受け取ることができるため、他の例外をラップして、新しい例外としてスローできます。

たとえば、次のように使用できます：

```kotlin
try {
    // 例外が発生する可能性のあるコード
    someFunction()
} catch (e: SomeException) {
    // 例外をラップして再スロー
    throw CustomException("An error occurred", e)
}
```

この場合、 CustomException の cause プロパティに SomeException がセットされ、スタックトレースをたどることで元の例外の情報も確認できます。


